### ISSUE TITLE
NHL logo not resolving

### ISSUE THREAD

**Issue by Foxcon84** [taylorbourne/xteve_lazystream#27]
I see that the URL http://home.windstream.net/dgrodecki/images/nhl/nhl_logo2.jpg is used as the logo for the channels however it seems to not be loading. Is this expected? Btw thanks for all the work on this!

**Comment by tarkah** [comment]
Yeah doesn't seem to load anymore, I'll replace with a new logo. This is happening on my end with lazystream, so I'll fix things there.

**Comment by tarkah** [comment]
@Foxcon84 I've merged the fix into master. I'd recommend deleting your mount point `.xteve` folder and `playlist` folder before building / running the updated docker. If you made any settings changes in xteve, I'd backup that settings `.xteve/settings.json`  and restoring it after running the docker.

The reason you should do this is because those logos get "cached" on xteve side. You can try just deleting the `playlist` mounted folder and the `.xteve/xepg.json` file (I think that's where logos are cached) and see if things get recreated properly.

**Comment by tarkah** [comment]
Until @taylorbourne pushes this to dockerhub, you'll have to build it from this repo (I don't have access to push the image there)

**Comment by Foxcon84** [comment]
@tarkah Awesome! I'll build it shortly and make your suggested changes before updating the container

**Comment by tarkah** [comment]
@Foxcon84 I lied, I forgot he set up auto-publish on master to dockerhub. The `latest` tag should pull the changes I made :)

**Comment by Foxcon84** [comment]
Oh even easier 😀

**Comment by taylorbourne** [comment]
@Foxcon84 realizing now that I'm here that both of these issues were from the same person! Nevertheless, `v1.1.3` has been released and should cover both of your issues 👍
