### ISSUE TITLE
Have to 'Refresh Guide' Everyday on Plex

### ISSUE THREAD

**Issue by echefel** [taylorbourne/xteve_lazystream#63]
Hi guys - 
It seems that every single day plex shows "the guide is empty please verify your channel mappings and refresh the guide" and I have to manually refresh the guide around the time of game starts in order for it to populate. IF i refresh guide way early in the day, it just shows the guide is empty.

Why is that? Is there an option im missing?

**Comment by chesh1r3k** [comment]
I just think getting that URL is just missing some steps, as I just set this up today. After going to your Live TV section and pressing F12 to bring up developer tools in Chrome, I had to click on the > icon at the top and then select Network. After that, I set the filter for reloadGuide? and then followed the rest of the instructions.

**Comment by chanrwm** [comment]
So I put in my URL with those instructions and plexUpdateURL w/ the values from the developer tool console and it doesn't seem to work still with no updates to Plex. Looking at the cronjob.sh I tried to manually push the URL I copied via curl like in the script and I'm getting HTTP 401 Unauthorized. Logs don't seem to show anything either. Is there some kind of Plex Token change I need to do?

**Comment by taylorbourne** [comment]
Yeah it's not working properly for some reason, I'm taking a look

**Comment by echefel** [comment]
Just FYI to everyone
Changing the settings within PLEX to auto refresh does the trick.

Just click on Live TV and DVR, then the 3 dots, settings. then on the right click DVR setting

![dxru25sveaw71](https://user-images.githubusercontent.com/87033032/139602577-d354b8e4-4d3e-4fdf-bcd3-71bed06007b6.jpg)
gs

**Comment by chanrwm** [comment]
I had trouble with auto refresh not working. I noticed the XMLs would usually update with games around noon and set Plex to update between 2-3PM but it never picked up the new Lazystream EPG over the last three days. 

My setup also has an HDHomerun so not sure if that has anything to do with it and that always updated fine.

**Comment by chesh1r3k** [comment]
@chanrwm How are you using a HDhomerun and Xteve? Custom XML guide data instead of the built in EPG?

**Comment by taylorbourne** [comment]
@echefel thanks for the tip there – but we should still be able to hit Plex to tell it to update at will instead of trying to trigger at the right time. I'll let you know when I come up with something.. seems like mine works _sometimes_ so just trying to see if I can find the culprit.

@chesh1r3k you can add multiple sources into Plex 👍

**Comment by chesh1r3k** [comment]
@taylorbourne Oh, I know you can have multiple tuners, just not different types of guides, the last time I checked.  I'm running a second Plex server so that I can have Xteve w. an XML TV guide and HDHomeruns w/ EPG on the main. Didn't know if Plex finally fixed this. Might be time to find an XMLTV source for my HDHomeruns.

**Comment by chanrwm** [comment]
@chesh1r3k You have to grab EPG via zap2it (free) for the stations that you have feeds for. Sign up for an account there then add your IP/HDHomeRun sources in the XTeve playlist section. Set up a cron job to pull the Zap2It lineups and then import them to XTeVe in the XMLTV section, then change your mappings and build your map using the Zap2it data. I do not use Plex's EPG since I want to remap my channels to what I want mixing in different IP sources + HDHomerun

**Comment by taylorbourne** [comment]
@chanrwm @chesh1r3k 

Ohh sorry, I made some incorrect assumptions! Keep in mind, this bundle comes with guide2go that works with schedules direct. I should note, SD is like $3/mo or $25/yr.

I'm working on updating the plex update url to use a curl request. I think we're missing some headers that allow the call to work properly.

**Comment by chanrwm** [comment]
@taylorbourne yea I was using SD before I realized Zap2It provides the same thing for free and it was supported in some xTeVe so I used that instead.
