### ISSUE TITLE
[ERROR] unexpected end of JSON input () - EC: 0

### ISSUE THREAD

**Issue by MaDTaZ** [taylorbourne/xteve_lazystream#78]
After installing 1.5.2 I am getting this error right after it doing this function.

| crond[393]: crond (busybox 1.34.1) started, log level 8
nhl_games_1  | [services.d] done.
nhl_games_1  | 2021/12/12 10:28:13 [xTeVe] [ERROR] unexpected end of JSON input () - EC: 0

I put back 1.5.1 and if works just fine. I am now seeing it with 1.5.1 as well

**Comment by taylorbourne** [comment]
What’s in your `settings.json` in your xTeVe directory? Searching the xTeVe discord with your error returned quite a few results.

**Comment by taylorbourne** [comment]
Ok I searched around their Discord for you a bit more because I'm just sitting here watching TV – I'm guessing you'll find that `settings.json` is empty and has been corrupted. You can delete it and I believe xTeVe will generate a new one. 

Though I would try to restore from a backup if possible, that way you don't have to start from scratch if you have a bunch of changes. 

A last resort idea might be to delete the file and create a new one using our defaults in this repo. (https://github.com/taylorbourne/xteve_lazystream/blob/master/root/defaults/xteve-settings.json)

What I can't find is any information pointing to why this happens. Most users report a stable environment and bam, corrupted settings. Backups should be generated by default so you should be good.

**Comment by MaDTaZ** [comment]
Thanks

I just removed the whole .xteve folder and then it recreated which worked.

**Comment by taylorbourne** [comment]
No worries! Appreciate you opening an issue, always good to track this stuff. Unfortunately this looks to be something wonky xTeVe does under the hood (occasionally? on certain setups? under certain conditions? lol) so it's unlikely it'll be fixed any time soon.

I've made note of it though and will add it to my list of issues for my fork of xTeVe. Trying to fix some common issues, bake some of our functionality into the core app, rewrite the entire api, and build a new frontend from the ground up (mobile friendly, yay). It'll be nice when it's done but like I've said in other threads I'm likely months out from even releasing a beta.

**Comment by MaDTaZ** [comment]
Sounds good looking forward in check it out alway like testing out stuff.
